metadata:
  namespace: mybookinfo
spec:
  replicas: 1
  template:
    spec:
      #volumes:
      #  - name: config
      #    gitRepo:
      #      repository: 'https://github.com/jstrachan/sample-springboot-config.git'
      #      revision: 667ee4db6bc842b127825351e5c9bae5a4fb2147
      #      directory: .
      #containers:
      #  - volumeMounts:
      #      - name: config
      #        mountPath: /app/config
      #    env:
      #      - name: KUBERNETES_NAMESPACE
      #        valueFrom:
      #          fieldRef:
      #            apiVersion: v1
      #            fieldPath: metadata.namespace
      containers:
      - env:
          #the best way is in rating project
          - name: spring.datasource.url
            value: "jdbc:postgresql://192.168.92.1:5432/reviewdb"
          - name: spring.datasource.username
            value: "bookinfo"
          - name: spring.datasource.password
            value: "bookinfo"
      serviceAccount: mybookinfo-sa