apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: mybookinfo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mybookinfo-sa
  namespace: mybookinfo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-mybookinfo-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: mybookinfo-sa
    namespace: mybookinfo