spec:
  replicas: 2
  template:
    spec:
      #volumes:
      #  - name: config
      #    gitRepo:
      #      repository: 'https://github.com/jstrachan/sample-springboot-config.git'
      #      revision: 667ee4db6bc842b127825351e5c9bae5a4fb2147
      #      directory: .
      #containers:
      #  - volumeMounts:
      #      - name: config
      #        mountPath: /app/config
      #    env:
      #      - name: KUBERNETES_NAMESPACE
      #        valueFrom:
      #          fieldRef:
      #            apiVersion: v1
      #            fieldPath: metadata.namespace
      serviceAccount: super-sa